apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  progressDeadlineSeconds: 9
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - image: ghcr.io/dhpup/guestbook:0.1.40
        name: guestbook
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-a
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app-a
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook
spec:
  progressDeadlineSeconds: 3
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  strategy:
    canary:
      canaryService: preview-guestbook
      steps:
      - setWeight: 50
      - pause: {}
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: ghcr.io/dhpup/guestbook:0.1.40
        name: guestbook
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: preview-guestbook
spec:
  ports:
  - name: https
    port: 80
    targetPort: https
  selector:
    app: guestbook
  type: ClusterIP
