apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/dhpup/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/non-prod/dev
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/non-prod/dev
          images:
          - image: ghcr.io/dhpup/guestbook
      - uses: kustomize-build
        config:
          path: ./src/app-a/non-prod/dev
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/non-prod/dev
      - uses: argocd-update
        config:
          apps:
          - name: app-a-non-prod-dev
            sources:
            - repoURL: https://github.com/dhpup/kargo-b.git
              desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/dhpup/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/non-prod/uat
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/base
          images:
          - image: ghcr.io/dhpup/guestbook
      - uses: kustomize-build
        config:
          path: ./src/app-a/non-prod/uat
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/non-prod/uat
      - uses: argocd-update
        config:
          apps:
          - name: app-a-non-prod-uat
            sources:
            - repoURL: https://github.com/dhpup/kargo-b.git
              desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-a-cluster-01
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/dhpup/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-a/cluster-01
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/base
          images:
          - image: ghcr.io/dhpup/guestbook
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-a/cluster-01
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-a/cluster-01
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-a-cluster-01
            sources:
            - repoURL: https://github.com/dhpup/kargo-b.git
              desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-a-cluster-02
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-a-cluster-01
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/dhpup/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-a/cluster-02
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/base
          images:
          - image: ghcr.io/dhpup/guestbook
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-a/cluster-02
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-a/cluster-02
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-a-cluster-02
            sources:
            - repoURL: https://github.com/dhpup/kargo-b.git
              desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-a-cluster-03
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-a-cluster-01
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/dhpup/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-a/cluster-03
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/base
          images:
          - image: ghcr.io/dhpup/guestbook
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-a/cluster-03
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-a/cluster-03
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-a-cluster-03
            sources:
            - repoURL: https://github.com/dhpup/kargo-b.git
              desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-a-cluster-03
      - region-a-cluster-02
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b-cluster-01
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-b
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/dhpup/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-b/cluster-01
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/base
          images:
          - image: ghcr.io/dhpup/guestbook
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-b/cluster-01
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-b/cluster-01
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-b-cluster-01
            sources:
            - repoURL: https://github.com/dhpup/kargo-b.git
              desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b-cluster-02
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-b
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/dhpup/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-b/cluster-02
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/base
          images:
          - image: ghcr.io/dhpup/guestbook
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-b/cluster-02
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-b/cluster-02
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-b-cluster-02
            sources:
            - repoURL: https://github.com/dhpup/kargo-b.git
              desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: region-b-cluster-03
  namespace: app-a
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  shard: kargo-agent
  requestedFreight:
  - origin:
      kind: Warehouse
      name: app-a
    sources:
      stages:
      - region-b
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/dhpup/kargo-b.git
          checkout:
          - branch: main
            path: ./src
          - branch: app-a/region-b/cluster-03
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/app-a/base
          images:
          - image: ghcr.io/dhpup/guestbook
      - uses: kustomize-build
        config:
          path: ./src/app-a/region-b/cluster-03
          outPath: ./out/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: app-a/region-b/cluster-03
      - uses: argocd-update
        config:
          apps:
          - name: app-a-region-b-cluster-03
            sources:
            - repoURL: https://github.com/dhpup/kargo-b.git
              desiredCommitFromStep: commit