apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-a
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
      - stage: uat
  template:
    metadata:
      name: app-a-non-prod-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: app-a-non-prod:{{stage}}
    spec:
      project: kargo-b-demo
      source:
        repoURL: https://github.com/dhpup/kargo.git
        targetRevision: app-a/non-prod/{{stage}}
        path: app-a/non-prod/{{stage}}
      destination:
        name: mac1
        namespace: app-a-non-prod-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
